php-version = "8.5.0"

[source]
workspace = "."
paths = ["src", "tests"]
includes = ["vendor"]
excludes = []

[formatter]
print-width = 120
use-tabs = true
array-table-style-alignment = false
empty-line-between-same-symbols = false
preserve-breaking-member-access-chain = true
preserve-breaking-argument-list = true
preserve-breaking-parameter-list = true
preserve-breaking-attribute-list = true
preserve-breaking-conditional-expression = true
preserve-breaking-condition-expression = true
preserve-breaking-binary-expression = true

[linter]
integrations = []

[linter.rules]
cyclomatic-complexity = { enabled = false }
kan-defect = { enabled = false }
literal-named-argument = { enabled = false }
no-else-clause = { enabled = false }
no-boolean-flag-parameter = { enabled = false }
too-many-methods = { enabled = false }
excessive-parameter-list = { enabled = false }
